### ISSUE TITLE
More efficient way to comment out a block of code

### ISSUE THREAD

**Issue by RavenHex1296** [walliuswilliam/machine-learning#1]
I noticed you were typing # for every line you wanted to comment out. Instead of doing that, it is probably easier and less time consuming to put that block of code into
'''
code
'''
like this. In the end though, it does the same thing.

**Comment by walliuswilliam** [comment]
thanks for the tip, I didn't know that, but if you want to comment out more than 1 line, you can highlight them, then press ctrl+/ to add the # for each line. in my opinion, this is better since you can either uncomment them 1 at a time, as you need them or uncomment them all by re-highlighting and pressing ctrl+/ again.
